### ISSUE TITLE
add the product count

### ISSUE THREAD

**Issue by nameoftheuser1** [nameoftheuser1/medmartbck#14]
add the product count in the dashboard controller

**Comment by nameoftheuser1** [comment]
@ikawlangsapatna143 @VillalobosCarla  eto naman try ninyo gawin

**Comment by ikawlangsapatna143** [comment]
Total count ba pare

**Comment by nameoftheuser1** [comment]
> Total count ba pare
> 

opo bilang ng lahat ng product

**Comment by VillalobosCarla** [comment]
be okay na check mo nga kung tama
